### ISSUE TITLE
Wink Hub translator broken with recent change that moves the function providerSchemaToPlatformSchema outside of the Translator class.

### ISSUE THREAD

**Issue by shalinijoshi19** [openT2T/translators#129]
CLI is broken as are the existing cloud unit tests that work with the getplatforms() API;
Onboarding + refresh is not affected. 

------------ ERROR-platforms
[TypeError: Cannot read property '_getOpent2tInfo' of undefined]
TypeError: Cannot read property '_getOpent2tInfo' of undefined
    at C:\opent2t\sj\cloud\node\node_modules\opent2t-translator-com-wink-hub\opent2t.p.hub\com.wink.hub\js\thingTranslator.js:23:31
    at Array.forEach (native)
    at providerSchemaToPlatformSchema (C:\opent2t\sj\cloud\node\node_modules\opent2t-translator-com-wink-hub\opent2t.p.hub\com.wink.hub\js\thingTranslator.js:21:17)
    at C:\opent2t\sj\cloud\node\node_modules\opent2t-translator-com-wink-hub\opent2t.p.hub\com.wink.hub\js\thingTranslator.js:94:13
    at tryCatcher (C:\opent2t\sj\cloud\node\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\opent2t\sj\cloud\node\node_modules\bluebird\js\release\promise.js:510:31)
    at Promise._settlePromise (C:\opent2t\sj\cloud\node\node_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (C:\opent2t\sj\cloud\node\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (C:\opent2t\sj\cloud\node\node_modules\bluebird\js\release\promise.js:691:18)
    at Async._drainQueue (C:\opent2t\sj\cloud\node\node_modules\bluebird\js\release\async.js:138:16)
    at Async._drainQueues (C:\opent2t\sj\cloud\node\node_modules\bluebird\js\release\async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\opent2

**Comment by danielrischar** [comment]
This'll be fixed by PR #128 as soon as it gets approved.

**Comment by shalinijoshi19** [comment]
Great thanks!
